version: "3.9"

services:
  ml_api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    # environment variables to suppress TensorFlow logging and disable oneDNN optimizations for better compatibility in container environments 
    environment:
      - TF_CPP_MIN_LOG_LEVEL=3
      - TF_ENABLE_ONEDNN_OPTS=0

    container_name: evoastra_team_E_api

    ports:
      - "8000:8000"

    volumes:
      - ../models:/app/models
      - ../data:/app/data

    restart: always